### ISSUE TITLE
Runtime Error after building the app in Ionic 4

### ISSUE THREAD

**Issue by carlos-jerez** [ralscha/blog#21]
Hi, 
I get this error after following the tutorial. I use Ionic Cli 4.1.2

ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at ChangeFilter.notFirstAndEmpty (vendor.js:181841)
    at NgxEchartsDirective.ngOnChanges (vendor.js:181948)
    at checkAndUpdateDirectiveInline (vendor.js:13831)
    at checkAndUpdateNodeInline (vendor.js:15359)
    at checkAndUpdateNode (vendor.js:15302)
    at debugCheckAndUpdateNode (vendor.js:16195)
    at debugCheckDirectivesFn (vendor.js:16136)
    at Object.eval [as updateDirectives] (ng:///AppModule/Chart1Page.ngfactory.js:39)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.js:16121)
    at checkAndUpdateView (vendor.js:15268)
    at ChangeFilter.notFirstAndEmpty (vendor.js:181841)
    at NgxEchartsDirective.ngOnChanges (vendor.js:181948)
    at checkAndUpdateDirectiveInline (vendor.js:13831)
    at checkAndUpdateNodeInline (vendor.js:15359)
    at checkAndUpdateNode (vendor.js:15302)
    at debugCheckAndUpdateNode (vendor.js:16195)
    at debugCheckDirectivesFn (vendor.js:16136)
    at Object.eval [as updateDirectives] (ng:///AppModule/Chart1Page.ngfactory.js:39)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.js:16121)
    at checkAndUpdateView (vendor.js:15268)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:6175)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
defaultErrorLogger @ vendor.js:2873

**Comment by ralscha** [comment]
Hi

Works fine on my computer with Ionic CLI 4.1.2

Can you compare your package.json with mine. Maybe you use a different version of a library.
https://github.com/ralscha/blog/blob/master/echarts/package.json

**Comment by ralscha** [comment]
Could this be the problem? Missing rxjs-compat
https://stackoverflow.com/a/50468954
